import { Inter, Mulish } from 'next/font/google';
import './globals.css';
import Header from '@/components/global';
import Footer from '@/components/global/Footer';

const mulish = Mulish({
    weight: ['400', '700', '900', '300', '200'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata = {
    title: 'Starconcord',
    description: 'Generated by Starconcord',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={mulish.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
